version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: alurafake-db
    restart: always
    environment:
      MYSQL_DATABASE: alurafake
      MYSQL_ROOT_PASSWORD: admin123
    ports:
      - "8888:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - alurafake-network

volumes:
  db_data:

networks:
  alurafake-network:
    driver: bridge
